// <auto-generated />
using System;
using CoffeeMachine.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeMachine.Persistence.Migrations
{
    [DbContext(typeof(CoffeeMachineDbContext))]
    [Migration("20190131213906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoffeeMachine.Domain.Entities.BadgeLastOrder", b =>
                {
                    b.Property<int>("BadgeLastOrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BadgeNo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("OrderId");

                    b.HasKey("BadgeLastOrderId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("BadgeLastOrder");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Entities.DrinkType", b =>
                {
                    b.Property<int>("DrinkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DrinkTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("DrinkTypeName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("PictureUrl")
                        .HasColumnType("ntext");

                    b.HasKey("DrinkTypeId");

                    b.ToTable("DrinkType");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DrinkTypeId");

                    b.Property<bool>("IsOwnMug");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SugarLevel");

                    b.HasKey("OrderId");

                    b.HasIndex("DrinkTypeId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Entities.BadgeLastOrder", b =>
                {
                    b.HasOne("CoffeeMachine.Domain.Entities.Order", "Order")
                        .WithOne("BadgeLastOrder")
                        .HasForeignKey("CoffeeMachine.Domain.Entities.BadgeLastOrder", "OrderId")
                        .HasConstraintName("FK_BadgeLastOrder_Order")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Entities.Order", b =>
                {
                    b.HasOne("CoffeeMachine.Domain.Entities.DrinkType", "DrinkType")
                        .WithMany("Order")
                        .HasForeignKey("DrinkTypeId")
                        .HasConstraintName("FK_Order_DrinkType")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
